import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex">
          {/* MENU */}
          <div className="w-[14%] md:w[8%]">
            <span className="flex items-center justify-center lg:justify-start gap-2">go-via</span>
            <Menu/>
          </div>
          {/* CONTENT */}
          <div className="w-[86%] md:w[92%] bg-[#7F8FA] overflow-scroll">content
          <Navbar/>
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
